const productos = [
  {
    nombre: "Al Final Del Tunel",
    artista: "Kold",
    genero: "minimal",
    id: 1,
    imagen: "./media/al-final-del-tunel-kold.jpg",
    sound: "./media/KOLD - Al Final Del Túnel (Original Mix).mp3",
    precio: 200,
    categoria: {
      nombre: "minimal",
      id: "minimal",
    },
  },
  {
    nombre: "Dark Sequence",
    artista: "Kold",
    genero: "minimal",
    id: 2,
    imagen: "./media/al-final-del-tunel-kold.jpg",
    sound: "./media/KOLD - Dark Sequence (Original Mix).mp3",
    precio: 200,
    categoria: {
      nombre: "minimal",
      id: "minimal",
    },
  },
  {
    nombre: "Ninja",
    artista: "JØKR",
    genero: "minimal",
    id: 3,
    imagen: "./media/jokr-head-hunter-EP.jpg",
    sound: "./media/JØKR - Ninja (Original Mix) Bandcamp Exclusive.mp3",
    precio: 200,
    categoria: {
      nombre: "minimal",
      id: "minimal",
    },
  },
  {
    nombre: "All Night Long",
    artista: "JØKR",
    genero: "minimal",
    id: 4,
    imagen: "./media/jokr-head-hunter-EP.jpg",
    sound:
      "./media/JØKR - All Night Long (Original Mix) Bandcamp Exclusive.mp3",
    precio: 200,
    categoria: {
      nombre: "minimal",
      id: "minimal",
    },
  },
  {
    nombre: "Head Hunter",
    artista: "JØKR",
    genero: "minimal",
    id: 5,
    imagen: "./media/jokr-head-hunter-EP.jpg",
    sound: "./media/JØKR - Ninja (Original Mix) Bandcamp Exclusive.mp3",
    precio: 200,
    categoria: {
      nombre: "minimal",
      id: "minimal",
    },
  },
  {
    nombre: "Making The Goove",
    artista: "Anvii",
    genero: "house",
    id: 6,
    imagen: "./media//Anvii-Making-the-groove-EP.jpg",
    sound: "./media/Anvii - Making The Groove (Original Mix).mp3",
    precio: 200,
    categoria: {
      nombre: "house",
      id: "house",
    },
  },
  {
    nombre: "Rojaiju",
    artista: "Anvii",
    genero: "house",
    id: 7,
    imagen: "./media//Anvii-Making-the-groove-EP.jpg",
    sound: "./media/Anvii - Making The Groove (Original Mix).mp3",
    precio: 200,
    categoria: {
      nombre: "house",
      id: "house",
    },
  },
  {
    nombre: "Check This Out",
    artista: "Anvii",
    genero: "house",
    id: 8,
    imagen: "./media//Anvii-Making-the-groove-EP.jpg",
    sound: "./media/Anvii - Making The Groove (Original Mix).mp3",
    precio: 200,
    categoria: {
      nombre: "house",
      id: "house",
    },
  },
  {
    nombre: "White Lights",
    artista: "Fenoma",
    genero: "house",
    id: 9,
    imagen: "./media/Fenoma-White-Lights-EP.jpg",
    sound: "../media/Fenoma - White Lights (Original Mix).mp3",
    precio: 200,
    categoria: {
      nombre: "house",
      id: "house",
    },
  },
  {
    nombre: "Feel It",
    artista: "Fenoma",
    genero: "house",
    id: 10,
    imagen: "./media/Fenoma-White-Lights-EP.jpg",
    sound: "./media/Anvii - Making The Groove (Original Mix).mp3",
    precio: 200,
    categoria: {
      nombre: "house",
      id: "house",
    },
  },
];
